name: Pass Custom Variables In Workflow Step

on:
  workflow_dispatch:

jobs:
  Linux-Runner-Job:
    runs-on: ubuntu-latest
    steps:
      - run: env

  Windows-Runner-Job:
    runs-on: windows-latest
    steps:
      - run: env
