name: Default Environment Variables

on:
  workflow_dispatch:

jobs:
  Linux-Runner-Job:
    runs-on: ubuntu-latest
    
    steps:
      - run: env

# print triggering event name

      - name: Print Event (Runner Environment Variable)
        run: echo "Trigger event is $GITHUB_EVENT_NAME"

      - name: Print Event (Context Variable)
        run: echo "Home directory is ${{ github.event_name }}"

# print home directory

      - name: Print Home Directory (Runner Environment Variable)
        run: echo "Home directory is $HOME"

      - name: Print Home Directory (Context Variable)
        run: echo "Home directory is ${{ runner.home }}"

  Windows-Runner-Job:
    runs-on: windows-latest
    
    steps:
      - run: env

# print triggering event name

      - name: Print Event (Runner Environment Variable)
        run: echo "Trigger event is $env:GITHUB_EVENT_NAME"

      - name: Print Event (Context Variable)
        run: echo "Home directory is ${{ github.event_name }}"

# print home directory
        
      - name: Print Home Directory (Runner Environment Variable)
        run: echo "Home directory is $env:USERPROFILE"
      
      - name: Print Home Directory (Context Variable)      
        run: echo "Home directory is ${{ runner.home }}"
